# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f079a644cf4cc81473d5b00cae8f5ae97c1fce56ed42635b6a877836f1a10af5bda0eee4bff903b0a777f3022c7f973c357597e73c460fab1fc5e62c6b2586c

test:
  secret_key_base: 29c53ebf4439065f7c6e19912f35c37c0c63003e840e2bafabdc0fedb9ba1e6b857f72207c81f68d263abfa123174b5bb4db9baede64703615856aa8822da562

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
